- _posts/creative-and-web-development.md
- _posts/eight-ways-to-Improve-staff-motivation.md
- _posts/offshore-web-development.md
- _posts/split-stack-web-development.md
- _posts/the-baltic-e-success.md
- _posts/tips-for-task-estimating.md
- ссылка на jira: COM-2098
- стенд: http://feat-com-2098.csssr-new-blog.csssr.cloud/
> COM-2098: Update tag in posts

- _posts/how-close-your-outsourced-team-should-be-located-pros-and-cons.md
- ссылка на jira: https://jira.csssr.io/browse/COM-2126
- стенд: http://feat-com-2126.csssr-new-blog.csssr.cloud/
> feat: COM-2126 Добавил alt и поменял размер h2

- components/error/Error404Page.jsx
- data/navItems.js
- ссылка на jira: https://jira.csssr.io/browse/COM-2208
- стенд: http://feat-com-2208.csssr-new-blog.csssr.cloud/
> feat: COM-2208 Добавил русский текст на странице 404

- _posts/how-close-your-outsourced-team-should-be-located-pros-and-cons.md
- components/Post/Body/Body.styles.js
- components/Post/Body/ParagraphWithImage/ParagraphWithImage.styles.js
- ссылка на jira: https://jira.csssr.io/browse/COM-2126
- стенд: http://feat-com2126.csssr-new-blog.csssr.cloud/
> feat: COM-2126 Исправил отступы в статье

- components/Meta.jsx
- components/Post/Post.jsx
- components/main/MainPage.jsx
- ссылка на jira: COM-2131
- стенд: http://com-2131.csssr-new-blog.csssr.cloud/
> COM-2131: Updated posts meta tags

- components/Post/Header/Header.jsx
- components/error/Error404Page.jsx
- components/main/Categories/Categories.jsx
- components/main/Posts/PostCard/PostCard.jsx
> COM-2223: поправил роутинг

- components/Layout/Layout.jsx
- data/footerLinks.js
- ссылка на jira: COM-_2247
- стенд: http://feat-com-2247.csssr-new-blog.csssr.cloud/
> COM-2247: Обновил контент футтера

- pages/_document.js
- utils/getGtmId.js
- ссылка на jira: COM-2058
- стенд: http://COM-2058.csssr-new-blog.csssr.cloud/
> COM-2058: ru gtm

- pages/[language]/[category]/[page].js
- pages/[language]/[category]/index.js
- pages/[language]/index.js
- fix posts orders on different pages
- ссылка на jira: COM-2425
- стенд: http://fix-com-2425.csssr-new-blog.csssr.cloud/
> fix(pages): COM-2425

- _posts/en/offshore-web-development.md
- components/Post/Body/Body.styles.js
- ссылка на jira: COM-2459
- стенд: http://fix-com-2459.csssr-new-blog.csssr.cloud/
> fix: COM-2459 Поправил смещение текста сравнения в статье

- utils/client/cleaningTitle.js
- ссылка на jira: COM-2466
- стенд: http://fix-com-2466.csssr-new-blog.csssr.cloud/
> fix: COM-2466 Улучшил cleaningTitle

- _posts/ru/qa-codex.md
> fix:(article): COM-2508 Поправил ссылки в конце статьи

- utils/sentry.js
- ссылка на jira: COM-2090
- стенд: http://COM-2090.csssr-new-blog.csssr.cloud/
> COM-2090: send sentry messages only in production env

- components/Post/Body/Body.styles.js
- ссылка на jira: COM-2522
- стенд: http://fix-com-2522.csssr-new-blog.csssr.cloud/
> fix: COM-2522 Поправил отступ от абзаца с буквицей

- components/Layout/Layout.styles.js
- ссылка на jira: COM-2650
- стенд: http://fix-com-2650.csssr-new-blog.csssr.cloud/
- [+] PR в ветку релиза
- [+] Указаны ревьюеры
> [fix: COM-2650] Removed content indents

- _posts/en/tips-for-task-estimating.md
- ссылка на jira: https://jira.csssr.io/browse/COM-2545
- стенд: http://fix-com-2545.csssr-new-blog.csssr.cloud/
> fix: COM-2545 Post list fix

- components/CookiesPopup/CookiesPopup.styles.js
> fix(CookiesPopup): COM-2764 update styles

- data/footerLinks.js
- data/headerLinks.js
- package.json
- yarn.lock
* https://jira.csssr.io/projects/COM/versions/12102
* стенд: http://release-com-ceses-des.csssr.cloud
> feat(header&footer): COM-2739, COM-2740

- _posts/en/tips-for-task-estimating.md
- pages/_document.js
- ссылка на jira: COM-2696
- ссылка на jira: COM-2660
- стенд: http://fix-com-2696.csssr-new-blog.csssr.cloud/
> Fix: COM-2696, COM-2660:  Исправил загрузку шрифта и title в статье

- components/Layout/Layout.styles.js
- ссылка на jira: COM-2542
- стенд: http://fix-com-2542.csssr-new-blog.csssr.cloud/
> fix: COM-2542 Убрал квадратики по ховеру на ссылках в футере

- data/footerLinks.js
- data/headerLinks.js
- package.json
- yarn.lock
* https://jira.csssr.io/projects/COM/versions/12102
> release: COM-CASES-DES

- data/footerLinks.js
- ссылка на jira: COM-2548
- стенд: http://fix-com-2548.csssr-new-blog.csssr.cloud/
> fix: COM-2548 Fix footer blog link

- package.json
- yarn.lock
> Dependabot update

- components/Post/Body/ParagraphWithImage/ParagraphWithImage.styles.js
- ссылка на jira: COM-2917, COM-2919
- стенд: http://fix-com-2917.csssr-new-blog.csssr.cloud/
> fix: COM-2917 News page: Picture fix on mobile

- components/Meta.jsx
- components/Post/Post.jsx
- components/main/MainPage.jsx
- scripts/generateRobotsTxt.js
- scripts/generateSitemapXml.js
* Looks like `router.asPath` always comes with dashes on both ends
> Fix: COM-2905

- components/main/Posts/PostCard/PostCard.jsx
- components/main/Posts/PostCard/PostCard.styles.js
- ссылка на jira: COM-2923
- стенд: http://fix-com-2923.csssr-new-blog.csssr.cloud/
> fix: COM-2923 Make News 512 block full clickable

- components/Post/Header/Header.styles.js
- components/Post/Subtitle/Subtitle.styles.js
- components/news512/News/News.styles.js
- components/news512/News/NewsList/NewsList.styles.js
- ссылка на jira: COM-2904, COM-2926, COM-2908
- стенд: http://fix-com-2904.csssr-new-blog.csssr.cloud/
> fix: COM-2904 Tag margin fix

- components/main/Pagination/Pagination.styles.js
- components/main/Posts/PostCard/PostCard.styles.js
- components/news512/News/News.jsx
- components/news512/News/News.styles.js
- components/news512/News/NewsList/NewsList.jsx
- components/news512/News/NewsList/NewsList.styles.js
- ссылка на jira: COM-2932
- стенд: http://com-2932.csssr-new-blog.csssr.cloud/
> [COM-2932]: Fix news number markup

- components/main/Categories/Categories.jsx
- components/main/Categories/Categories.styles.js
- components/main/MainPage.jsx
- components/news512/News/News.jsx
- components/news512/News/News.styles.js
- ссылка на jira: COM-2929
- стенд: http://com-2929.csssr-new-blog.csssr.cloud/
> [COM-2929]: Fix categories styles

- components/main/Categories/ActiveLine/ActiveLine.styles.js
- ссылка на jira: COM-2933
- стенд: http://com-2933.csssr-new-blog.csssr.cloud/
> [COM-2933]: Fix categories underline

- components/news512/News/News.jsx
- components/news512/News/News.styles.js
- components/news512/News/NewsList/NewsList.styles.js
- ссылка на jira: COM-2935
- стенд: http://com-2935.csssr-new-blog.csssr.cloud/
* стенд: http://release-news-512.csssr-new-blog.csssr.cloud
> [COM-2935]: News item hover fix

- .github/workflows/deploy_production.yml
- .github/workflows/deploy_testing.yml
- .github/workflows/run_lighthouse.yml
- lighthouserc.js
Я пока установил проверку на Lighthouse как обязательную для мержа в мастер, что бы её наглядно было видно в PR. Но, наверное, хорошо бы её там оставить и навсегда, я, если честно, до того как начал работать над этим таском вообще не знал что у нас на школе и на блоге крутится Lighthouse.
> refactor(workflows): COM-2085 move Lighthouse action to the new workflow

- components/news512/News/NewsList/NewsList.styles.js
- ссылка на jira: COM-2936
- стенд: http://com-2936.csssr-new-blog.csssr.cloud/
* стенд: http://release-NEWS-512.csssr-new-blog.csssr.cloud
> [COM-2936]: Align item rows

- package.json
- yarn.lock
- ссылка на jira: COM-2928
- стенд: http://com-2928.csssr-new-blog.csssr.cloud/
* стенд: http://release-NEWS-512.csssr-new-blog.csssr.cloud
> [COM-2928]: Align social icons

- components/news512/News/NewsList/NewsList.jsx
- ссылка на jira: COM-2942
- стенд: http://com-2942.csssr-new-blog.csssr.cloud/
* стенд: http://release-NEWS-512.csssr-new-blog.csssr.cloud
> [COM-2942]: Hide markup from news list title

- .github/pull_request_template.md
- jest.config.js
> refactor(github): COM-2900 update PR template

- components/Layout/Layout.jsx
- ссылка на jira: COM-2946
- стенд: http://com-2946.csssr-new-blog.csssr.cloud/
> [COM-2946]: Change logo link href

- components/Post/Header/NewsAudioLink/NewsAudioLink.jsx
- components/Post/Header/NewsAudioLink/NewsAudioLink.styles.js
> fix: COM-2972 Fix soundtrack image blinking on first hover

- components/Newsletter/Newsletter.styles.js
* jira release board: https://jira.csssr.io/projects/COM/versions/12406
* testing: https://release-blog-after-ny.csssr-new-blog.csssr.cloud/en
> [COM-2985]: Changed picture position

- components/Newsletter/ContactForm/ContactForm.jsx
* jira release board: https://jira.csssr.io/projects/COM/versions/12406
* testing: https://release-blog-after-ny.csssr-new-blog.csssr.cloud/en
> [COM-2986]: Added resetting email field after submit

- .gitignore
- components/Layout/Layout.styles.js
- data/headerLinks.js
- public/icons/header/our-projects.svg
> [COM-2954]: Modified site header

- components/Post/Post.styles.js
* jira release board: https://jira.csssr.io/projects/COM/versions/12406
* testing: http://release-blog-after-ny.csssr.cloud
> fix: COM-2989 Remove double scroll

- _posts/ru/unicorn-busters.md
- components/Post/Body/Body.jsx
* jira release board: https://jira.csssr.io/projects/COM/versions/12302
* testing: https://release-blpost-ru-3.csssr-new-blog.csssr.cloud/en
> [COM-2485]: Returned related article links

- _posts/ru/year-resume.md
* jira release board: https://jira.csssr.io/projects/COM/versions/12703
> [COM-3052]: Changed link address

- components/Post/Body/Body.jsx
- components/Post/Body/ReadMore/ReadMore.jsx
> [COM-3047]: Modified component title

- components/Post/Body/Comments/Comments.jsx
> [COM-3046]: Fixed doubled commento block

- _posts/ru/semantics-in-programming.md
> fix(article): COM-3140 fix indents in listings

- components/BenchmarkEmail/BenchmarkEmail.jsx
- components/BenchmarkEmail/BenchmarkEmail.styles.js
* jira release board: https://jira.csssr.io/projects/COM/versions/12732
* testing: http://release-benchmark-subscribe-page.csssr.cloud
> [COM-3195]: Added picture animation

- pages/_document.js
* jira release board: https://jira.csssr.io/projects/COM/versions/12732
* testing: http://release-benchmark-subscribe-page.csssr.cloud
> Removed Benchmark script from documents

- _posts/ru/lint-your-css.md
- _posts/ru/side-effects.md
> feat: COM-3272 Fixed gifs in 'Lint your css' article

- _posts/news512/news-141.md
- _posts/news512/news-142.md
- _posts/news512/news-143.md
- _posts/news512/news-144.md
- _posts/news512/news-145.md
- _posts/news512/news-146.md
- _posts/news512/news-147.md
- _posts/news512/news-148.md
- _posts/news512/news-149.md
- _posts/news512/news-150.md
- _posts/news512/news-151.md
- _posts/news512/news-152.md
- _posts/news512/news-153.md
- _posts/news512/news-154.md
- _posts/news512/news-155.md
> Cut short descriptions duplicates

- pages/[language]/[category]/[page].js
> fix(pages): COM-3324 update page generation logic

- components/ContactForm/ContactForm.jsx
- components/ContactForm/ContactForm.styles.js
- components/ContactForm/TextField/TextField.styles.js
- components/PostNewsletter/PostNewsletter.styles.js
- components/error/Error404Page.jsx
- components/error/ErrorPage.jsx
- utils/ruPathRegexp.js
- change language detection for ErrorPage
- comment check for setMessageHidden in ContactForm to reproduce error behavior on staging
* jira release board: https://jira.csssr.io/projects/COM/versions/12721
> Release: BLOG-EMAIL-SUBSCRIBE 

- components/Post/Post.jsx
- components/PostShare/PostShare.jsx
- next.config.js
> fix(components): COM-3359 Post meta

- components/PostNewsletter/PostNewsletter.styles.js
- components/PostShare/PostShare.styles.js
- update paddings for PostNewsLetter and PostShare
> fix(components): COM-3355 PostNewsLetter

- components/BenchmarkEmail/BenchmarkEmail.jsx
- components/BenchmarkEmail/TextField/TextField.jsx
- components/BenchmarkEmail/TextField/TextField.styles.js
- eslint, prettier fix
- update TextField's label padding
- switch TextField from uncotrollable to controlable component
* jira release board: https://jira.csssr.io/projects/COM/versions/12732
> fix(component): COM-3311 BenchmarkEmail

- components/BenchmarkEmail/TextField/TextField.styles.js
- update border-radius styles
* jira release board: https://jira.csssr.io/projects/COM/versions/12732
> fix(components): COM-3312 TextField

- components/Post/Body/Comments/Comments.styled.js
- add custom styles for login form for Commento
* jira release board: https://jira.csssr.io/projects/COM/versions/12731
> feat(components): COM-3193 Comments

- package.json
- yarn.lock
> fix(dependencies): COM-3337

- package.json
- yarn.lock
> fix(dependencies): COM-3408 Update core-design version

- components/Post/Body/Comments/Comments.styled.js
> feat: COM-3302, COM-3353 Fixed margin and size of comments avatar

- components/Post/Body/Comments/Comments.styled.js
> feat: COM-3388 Comments modal| Fixed margin between inputs

- components/Post/Body/Comments/Comments.styled.js
> feat: COM-3402 Changed margin between input and button

- components/Post/Body/Comments/Comments.styled.js
* jira release board: https://jira.csssr.io/projects/COM/versions/12731
* testing: http://release-blog-comments-style.csssr.cloud
> feat: COM-3405 Changed z-index for modal

- components/Post/Body/Comments/Comments.styled.js
> feat: COM-3406 Changed margin between input and signup button

- components/Post/Body/Comments/Comments.styled.js
> feat: COM-3404 Changed margin between comments and login button

- components/Post/Body/Comments/Comments.styled.js
> feat: COM-3386 Remove shadow from modal oauth buttons

- components/Post/Body/Comments/Comments.styled.js
> feat: COM-3387 Remove border radius from modal submit button

- components/Post/Body/Comments/Comments.styled.js
> feat: COM-3402 Fixed margin of modal buttons

- components/Post/Body/Comments/Comments.styled.js
> feat: COM-3429 Fixed comments textarea position

- components/Post/Body/Comments/Comments.styled.js
> feat: COM-3382 Mobile| Changed height of commento login modal

- components/Post/Body/Comments/Comments.styled.js
> feat: COM-3403 Changed margin between modal inputs

- components/Post/Body/Comments/Comments.styled.js
> feat: COM-3382 Fixed comments modal on mobile

- package.json
- yarn.lock
> feat: COM-3271 update core-design version

- components/Post/Body/Comments/Comments.styled.js
> fix: COM-3439 Fixed modal height on mobiles

- components/Post/Body/Comments/Comments.styled.js
> fix: COM-3438 Fixed position of options buttons on mobile

- components/Post/Header/NewsAudioLink/NewsAudioLink.styles.js
> feat: COM-3474 Fixed top margin of links block

- components/Post/Body/Comments/Comments.styled.js
> feat: COM-3479 Fixed position of error message

- components/ContactForm/ContactForm.styles.js
> fix: COM-3351 Submit button| Fixed text button aligning on mobile

- components/PostShare/PostShare.jsx
- components/PostShare/PostShare.styles.js
> feat: COM-3452 Removed aligning of share block on en

- components/error/ErrorPosts/ErrorPosts.jsx
> fix: COM-3482 Fix posts order

- package.json
- yarn.lock
> fix: COM-3481 Updated @csssr/core-design version

- components/error/ErrorCategories/ErrorCategories.styles.js
> fix: COM-3495 Fix ErrorCategories carryover

- components/PostNewsletter/PostNewsletter.styles.js
- components/PostShare/PostShare.styles.js
> fix: COM-3488 Fix PostNewsletter position

- _posts/ru/frontend-history-the-browser-that-could-do-everything.md
> fix(article): COM-3480 Fix frontend-history header type

- components/ContactForm/ContactForm.jsx
- components/ContactForm/ContactForm.styles.js
- components/ContactForm/TextField/TextField.styles.js
> fix: COM-3365 Mobile| Subscribe form fixes

- components/PostNewsletter/PostNewsletter.styles.js
> fix: COM-3360 Tablet| Fixed position of Post share block

- components/BenchmarkEmail/BenchmarkEmail.styles.js
- components/BenchmarkEmail/TextField/TextField.styles.js
> fix: COM-3372, COM-3373 Fix in the subscribe page

- components/ContactForm/TextField/TextField.styles.js
> fix: COM-3540 Fixed position of active placeholder

- components/ContactForm/ContactForm.styles.js
- components/ContactForm/TextField/TextField.styles.js
> fix: COM-3590 Fix label position in BenchmarkEmail

- components/ContactForm/TextField/TextField.styles.js
> fix: COM-3590 Fix label position

- e2e-tests/.vscode/tasks.json
- e2e-tests/e2e-tools.json
- e2e-tests/nightwatch/screenshots/base/Regression/07_404/404_(EN)/chrome-1920x1080.png
- e2e-tests/nightwatch/screenshots/base/Regression/07_404/404_(EN)/firefox-1920x1080.png
- e2e-tests/nightwatch/screenshots/base/Regression/07_404/404_(EN)/safari-1920x1080.png
- e2e-tests/nightwatch/screenshots/base/Regression/07_404/404_(RU)/chrome-1920x1080.png
- e2e-tests/nightwatch/screenshots/base/Regression/07_404/404_(RU)/firefox-1366x768.png
- e2e-tests/nightwatch/screenshots/base/Regression/07_404/404_(RU)/safari-800x600.png
- e2e-tests/nightwatch/tests/Regression/07 404.test.js
- e2e-tests/nightwatch/tests/pageObject/page404.js
* jira release board: https://jira.csssr.io/browse/e2e-COM-3594
* testing: https://blog.csssr.com/ru
- Added 404 page tests for both RU and EN locales
* screenshots
> COM-3594: E2E tests_added tests for the 404 page

- package.json
- yarn.lock
> feat: COM-3591 Updated core-design version

- .github/kuberta.yaml
- .github/workflows/deploy_testing.yml
> feat: COM-3160 Add slack notifications about builds

- components/Meta.jsx
> fix: COM-3572 Remove from code /feed.xml

- components/Layout/Layout.styles.js
> fix: COM-3600 Fix footer on rising height

- .storybook/preview.js
- .storybook/utils/getTransformSource.js
- components/Post/Body/Body.jsx
- components/PostNewsletter/PostNewsletter.jsx
- components/PostShare/PostShare.jsx
- components/PostShare/PostShare.styles.js
- stories/Caption.stories.mdx
- stories/Heading.stories.mdx
- stories/Img.stories.mdx
- stories/Note.stories.mdx
- stories/ParagraphWithImage.stories.mdx
- stories/PostShare.stories.jsx
- stories/Quote.stories.mdx
- stories/Separator.stories.mdx
- stories/Subtitle.stories.mdx
- stories/Table.stories.mdx
- stories/Video.stories.mdx
- stories/utils/gridDecorator.js
> fix: COM-3383 Fixed size of share block on En

- components/Newsletter/Newsletter.styles.js
- components/main/LatestNews/LatestNews.jsx
- components/main/LatestNews/LatestNews.styles.js
- components/main/Pagination/Pagination.styles.js
- utils/client/getDescription.js
- utils/client/sliceDescription.js
> fix: COM-3667-3670 Fix LatestNews and Pagination

- components/Post/Body/ReadMore/PostCard/PostCard.jsx
- components/Post/Body/ReadMore/PostCard/PostCard.styles.js
- components/Post/Body/ReadMore/PostCard/index.js
- components/Post/Body/ReadMore/ReadMore.jsx
> fix: COM-3671 Returned ReadMore old PostCard

- components/BenchmarkEmail/BenchmarkEmail.jsx
- components/BenchmarkEmail/BenchmarkEmail.styles.js
- components/ContactForm/FormStateMessage/FormStateMessage.jsx
- utils/validators/composeValidators.js
> feat: COM-3624 Fix new eslint remarks

- components/Post/Body/Body.styles.js
> fix: COM-3428 Fix square when link hover

- components/Layout/Layout.styles.js
> fix(styles): COM-3641 add bgc for main

- lighthouserc.js
> Обновил токен lighthouse

- _posts/news512/news-176.md
> Update short description

- components/ContactForm/ContactForm.styles.js
> fix: COM-3687 Fix police subscribe policy link

- components/error/Error404Page.jsx
- components/error/ErrorPosts/ErrorPostCard/ErrorPostCard.jsx
- components/error/ErrorPosts/ErrorPostCard/ErrorPostCard.styles.js
> fix: COM-3693 Fix images ErrorPostCard

- components/Post/Body/Body.styles.js
> COM-3697: Fix unnecessary space inside the text

- components/Post/Body/Body.styles.js
> COM-3428: Fix hovering link square

- _posts/news512/news-178.md
> Add news issue №178

- .github/kuberta.yaml
- .github/workflows/deploy_production.yml
Изменения не влияют на текущую работу, но понадобятся для уменьшение количества редиректов при использовании схемы `http`
> Change rewrite target for ingress

- components/PostNewsletter/NewsPodcast/NewsPodcast.jsx
- components/PostNewsletter/PostNewsletter.jsx
> COM-3692: Hide podcast link block in news

- components/ContactForm/ContactForm.styles.js
- components/main/Newsletter/Newsletter.styles.js
- data/newsletter.js
> COM-3688: Fix main newsletter

- _posts/en/type-systems-part-1.md
> Add author, fix publication date and typo

- components/Layout/Layout.styles.js
- package.json
- yarn.lock
> COM-3757: Update core-design
